// <auto-generated />
using System;
using DIY_Site.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DIY_Site.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240526175446_AddProjectsAndSupplies")]
    partial class AddProjectsAndSupplies
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DIY_Site.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icon = "fa-house",
                            Name = "Home Improvement"
                        },
                        new
                        {
                            Id = 2,
                            Icon = "fa-seedling",
                            Name = "Gardening"
                        },
                        new
                        {
                            Id = 3,
                            Icon = "fa-plug",
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 4,
                            Icon = "fa-pen-ruler",
                            Name = "Crafts"
                        },
                        new
                        {
                            Id = 5,
                            Icon = "fa-car",
                            Name = "Automotive"
                        },
                        new
                        {
                            Id = 6,
                            Icon = "fa-tree",
                            Name = "Woodworking"
                        });
                });

            modelBuilder.Entity("DIY_Site.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThumbnailURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoURL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Complete guide to renovating your basement.",
                            Name = "Basement Renovation",
                            ThumbnailURL = "https://example.com/thumbnails/basement.jpg",
                            VideoURL = "https://example.com/videos/basement.mp4"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Creating a raised garden bed for your backyard.",
                            Name = "Garden Bed Installation",
                            ThumbnailURL = "https://example.com/thumbnails/garden.jpg",
                            VideoURL = "https://example.com/videos/garden.mp4"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            Description = "Step-by-step guide to replacing a broken smartphone screen.",
                            Name = "Smartphone Repair",
                            ThumbnailURL = "https://example.com/thumbnails/smartphone-repair.jpg",
                            VideoURL = "https://example.com/videos/smartphone-repair.mp4"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            Description = "Learn how to change the oil in your vehicle to save on maintenance costs.",
                            Name = "Vehicle Oil Change",
                            ThumbnailURL = "https://example.com/thumbnails/oil-change.jpg",
                            VideoURL = "https://example.com/videos/oil-change.mp4"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 6,
                            Description = "Craft a stylish wooden coffee table with minimal tools.",
                            Name = "Wooden Coffee Table",
                            ThumbnailURL = "https://example.com/thumbnails/coffee-table.jpg",
                            VideoURL = "https://example.com/videos/coffee-table.mp4"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Description = "Simple techniques to fix leaks in household plumbing.",
                            Name = "Pipe Leaks Fix",
                            ThumbnailURL = "https://example.com/thumbnails/pipe-leak.jpg",
                            VideoURL = "https://example.com/videos/pipe-leak.mp4"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Description = "Explore different techniques for painting walls to refresh your home.",
                            Name = "Wall Painting Techniques",
                            ThumbnailURL = "https://example.com/thumbnails/wall-painting.jpg",
                            VideoURL = "https://example.com/videos/wall-painting.mp4"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 6,
                            Description = "Create an organizer for your tools using simple materials.",
                            Name = "Custom Tool Organizer",
                            ThumbnailURL = "https://example.com/thumbnails/tool-organizer.jpg",
                            VideoURL = "https://example.com/videos/tool-organizer.mp4"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            Description = "Make your own unique Christmas ornaments with easy-to-follow steps.",
                            Name = "Handmade Christmas Ornaments",
                            ThumbnailURL = "https://example.com/thumbnails/christmas-ornaments.jpg",
                            VideoURL = "https://example.com/videos/christmas-ornaments.mp4"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 6,
                            Description = "Build a cozy birdhouse for your garden.",
                            Name = "Birdhouse Construction",
                            ThumbnailURL = "https://example.com/thumbnails/birdhouse.jpg",
                            VideoURL = "https://example.com/videos/birdhouse.mp4"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            Description = "Create a small solar panel for your home projects.",
                            Name = "DIY Solar Panel",
                            ThumbnailURL = "https://example.com/thumbnails/solar-panel.jpg",
                            VideoURL = "https://example.com/videos/solar-panel.mp4"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 4,
                            Description = "Craft beautiful wall art with simple materials.",
                            Name = "Decorative Wall Art",
                            ThumbnailURL = "https://example.com/thumbnails/wall-art.jpg",
                            VideoURL = "https://example.com/videos/wall-art.mp4"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 1,
                            Description = "Update your kitchen cabinets with new faces.",
                            Name = "Kitchen Cabinet Refacing",
                            ThumbnailURL = "https://example.com/thumbnails/kitchen-cabinet.jpg",
                            VideoURL = "https://example.com/videos/kitchen-cabinet.mp4"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            Description = "Build a compost bin for your garden.",
                            Name = "DIY Compost Bin",
                            ThumbnailURL = "https://example.com/thumbnails/compost-bin.jpg",
                            VideoURL = "https://example.com/videos/compost-bin.mp4"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 3,
                            Description = "Guide to setting up a wireless speaker system for your home.",
                            Name = "Wireless Speaker Setup",
                            ThumbnailURL = "https://example.com/thumbnails/wireless-speaker.jpg",
                            VideoURL = "https://example.com/videos/wireless-speaker.mp4"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 6,
                            Description = "Build a sturdy and stylish bookshelf for your home.",
                            Name = "DIY Bookshelf",
                            ThumbnailURL = "https://example.com/thumbnails/bookshelf.jpg",
                            VideoURL = "https://example.com/videos/bookshelf.mp4"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 1,
                            Description = "Create a cozy outdoor fire pit for your backyard.",
                            Name = "Outdoor Fire Pit",
                            ThumbnailURL = "https://example.com/thumbnails/fire-pit.jpg",
                            VideoURL = "https://example.com/videos/fire-pit.mp4"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 6,
                            Description = "Build a comfortable dog house for your furry friend.",
                            Name = "DIY Dog House",
                            ThumbnailURL = "https://example.com/thumbnails/dog-house.jpg",
                            VideoURL = "https://example.com/videos/dog-house.mp4"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            Description = "Design and create a beautiful mosaic tile table.",
                            Name = "Mosaic Tile Table",
                            ThumbnailURL = "https://example.com/thumbnails/mosaic-table.jpg",
                            VideoURL = "https://example.com/videos/mosaic-table.mp4"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 2,
                            Description = "Set up a system to collect and use rainwater for your garden.",
                            Name = "Rainwater Harvesting System",
                            ThumbnailURL = "https://example.com/thumbnails/rainwater-harvesting.jpg",
                            VideoURL = "https://example.com/videos/rainwater-harvesting.mp4"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 3,
                            Description = "Build a custom power bank to charge your devices on the go.",
                            Name = "DIY Power Bank",
                            ThumbnailURL = "https://example.com/thumbnails/power-bank.jpg",
                            VideoURL = "https://example.com/videos/power-bank.mp4"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 1,
                            Description = "Install modern floating shelves to display your decor.",
                            Name = "Floating Shelves",
                            ThumbnailURL = "https://example.com/thumbnails/floating-shelves.jpg",
                            VideoURL = "https://example.com/videos/floating-shelves.mp4"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 2,
                            Description = "Create a miniature indoor garden with a DIY terrarium.",
                            Name = "DIY Terrarium",
                            ThumbnailURL = "https://example.com/thumbnails/terrarium.jpg",
                            VideoURL = "https://example.com/videos/terrarium.mp4"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 4,
                            Description = "Learn how to make your own soap with natural ingredients.",
                            Name = "Homemade Soap",
                            ThumbnailURL = "https://example.com/thumbnails/soap.jpg",
                            VideoURL = "https://example.com/videos/soap.mp4"
                        });
                });

            modelBuilder.Entity("DIY_Site.Models.Supply", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Supplies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Hammer",
                            ProjectId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Nails",
                            ProjectId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Lumber",
                            ProjectId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Soil",
                            ProjectId = 2
                        },
                        new
                        {
                            Id = 5,
                            Name = "Seeds",
                            ProjectId = 2
                        },
                        new
                        {
                            Id = 6,
                            Name = "Wood planks",
                            ProjectId = 2
                        },
                        new
                        {
                            Id = 7,
                            Name = "Replacement screen",
                            ProjectId = 4
                        },
                        new
                        {
                            Id = 8,
                            Name = "Toolkit",
                            ProjectId = 4
                        },
                        new
                        {
                            Id = 9,
                            Name = "Adhesive",
                            ProjectId = 4
                        },
                        new
                        {
                            Id = 10,
                            Name = "Engine oil",
                            ProjectId = 5
                        },
                        new
                        {
                            Id = 11,
                            Name = "Oil filter",
                            ProjectId = 5
                        },
                        new
                        {
                            Id = 12,
                            Name = "Funnel",
                            ProjectId = 5
                        },
                        new
                        {
                            Id = 13,
                            Name = "Wood planks",
                            ProjectId = 6
                        },
                        new
                        {
                            Id = 14,
                            Name = "Saw",
                            ProjectId = 6
                        },
                        new
                        {
                            Id = 15,
                            Name = "Sandpaper",
                            ProjectId = 6
                        },
                        new
                        {
                            Id = 16,
                            Name = "Varnish",
                            ProjectId = 6
                        },
                        new
                        {
                            Id = 17,
                            Name = "Plumber's tape",
                            ProjectId = 7
                        },
                        new
                        {
                            Id = 18,
                            Name = "Wrench",
                            ProjectId = 7
                        },
                        new
                        {
                            Id = 19,
                            Name = "Replacement pipes",
                            ProjectId = 7
                        },
                        new
                        {
                            Id = 20,
                            Name = "Paint",
                            ProjectId = 8
                        },
                        new
                        {
                            Id = 21,
                            Name = "Brushes",
                            ProjectId = 8
                        },
                        new
                        {
                            Id = 22,
                            Name = "Rollers",
                            ProjectId = 8
                        },
                        new
                        {
                            Id = 23,
                            Name = "Plywood",
                            ProjectId = 9
                        },
                        new
                        {
                            Id = 24,
                            Name = "Screws",
                            ProjectId = 9
                        },
                        new
                        {
                            Id = 25,
                            Name = "Drill",
                            ProjectId = 9
                        },
                        new
                        {
                            Id = 26,
                            Name = "Glitter",
                            ProjectId = 10
                        },
                        new
                        {
                            Id = 27,
                            Name = "Glue",
                            ProjectId = 10
                        },
                        new
                        {
                            Id = 28,
                            Name = "Ribbon",
                            ProjectId = 10
                        },
                        new
                        {
                            Id = 29,
                            Name = "Wood planks",
                            ProjectId = 11
                        },
                        new
                        {
                            Id = 30,
                            Name = "Nails",
                            ProjectId = 11
                        },
                        new
                        {
                            Id = 31,
                            Name = "Paint",
                            ProjectId = 11
                        },
                        new
                        {
                            Id = 32,
                            Name = "Solar cells",
                            ProjectId = 12
                        },
                        new
                        {
                            Id = 33,
                            Name = "Wiring",
                            ProjectId = 12
                        },
                        new
                        {
                            Id = 34,
                            Name = "Soldering kit",
                            ProjectId = 12
                        },
                        new
                        {
                            Id = 35,
                            Name = "Canvas",
                            ProjectId = 13
                        },
                        new
                        {
                            Id = 36,
                            Name = "Paint",
                            ProjectId = 13
                        },
                        new
                        {
                            Id = 37,
                            Name = "Brushes",
                            ProjectId = 13
                        },
                        new
                        {
                            Id = 38,
                            Name = "Cabinet faces",
                            ProjectId = 14
                        },
                        new
                        {
                            Id = 39,
                            Name = "Screws",
                            ProjectId = 14
                        },
                        new
                        {
                            Id = 40,
                            Name = "Drill",
                            ProjectId = 14
                        },
                        new
                        {
                            Id = 41,
                            Name = "Wood planks",
                            ProjectId = 15
                        },
                        new
                        {
                            Id = 42,
                            Name = "Nails",
                            ProjectId = 15
                        },
                        new
                        {
                            Id = 43,
                            Name = "Hinges",
                            ProjectId = 15
                        },
                        new
                        {
                            Id = 44,
                            Name = "Wireless speakers",
                            ProjectId = 16
                        },
                        new
                        {
                            Id = 45,
                            Name = "Wi-Fi router",
                            ProjectId = 16
                        },
                        new
                        {
                            Id = 46,
                            Name = "Mobile app",
                            ProjectId = 16
                        },
                        new
                        {
                            Id = 47,
                            Name = "Wood planks",
                            ProjectId = 17
                        },
                        new
                        {
                            Id = 48,
                            Name = "Saw",
                            ProjectId = 17
                        },
                        new
                        {
                            Id = 49,
                            Name = "Screws",
                            ProjectId = 17
                        },
                        new
                        {
                            Id = 50,
                            Name = "Drill",
                            ProjectId = 17
                        },
                        new
                        {
                            Id = 51,
                            Name = "Bricks",
                            ProjectId = 18
                        },
                        new
                        {
                            Id = 52,
                            Name = "Mortar",
                            ProjectId = 18
                        },
                        new
                        {
                            Id = 53,
                            Name = "Shovel",
                            ProjectId = 18
                        },
                        new
                        {
                            Id = 54,
                            Name = "Plywood",
                            ProjectId = 19
                        },
                        new
                        {
                            Id = 55,
                            Name = "Nails",
                            ProjectId = 19
                        },
                        new
                        {
                            Id = 56,
                            Name = "Paint",
                            ProjectId = 19
                        },
                        new
                        {
                            Id = 57,
                            Name = "Shingles",
                            ProjectId = 19
                        },
                        new
                        {
                            Id = 58,
                            Name = "Tiles",
                            ProjectId = 20
                        },
                        new
                        {
                            Id = 59,
                            Name = "Grout",
                            ProjectId = 20
                        },
                        new
                        {
                            Id = 60,
                            Name = "Table frame",
                            ProjectId = 20
                        },
                        new
                        {
                            Id = 61,
                            Name = "Adhesive",
                            ProjectId = 20
                        },
                        new
                        {
                            Id = 62,
                            Name = "Barrels",
                            ProjectId = 21
                        },
                        new
                        {
                            Id = 63,
                            Name = "Gutters",
                            ProjectId = 21
                        },
                        new
                        {
                            Id = 64,
                            Name = "Pipes",
                            ProjectId = 21
                        },
                        new
                        {
                            Id = 65,
                            Name = "Battery cells",
                            ProjectId = 22
                        },
                        new
                        {
                            Id = 66,
                            Name = "Charging circuit",
                            ProjectId = 22
                        },
                        new
                        {
                            Id = 67,
                            Name = "Enclosure",
                            ProjectId = 22
                        },
                        new
                        {
                            Id = 68,
                            Name = "Wood planks",
                            ProjectId = 23
                        },
                        new
                        {
                            Id = 69,
                            Name = "Brackets",
                            ProjectId = 23
                        },
                        new
                        {
                            Id = 70,
                            Name = "Drill",
                            ProjectId = 23
                        },
                        new
                        {
                            Id = 71,
                            Name = "Screws",
                            ProjectId = 23
                        },
                        new
                        {
                            Id = 72,
                            Name = "Glass container",
                            ProjectId = 24
                        },
                        new
                        {
                            Id = 73,
                            Name = "Soil",
                            ProjectId = 24
                        },
                        new
                        {
                            Id = 74,
                            Name = "Plants",
                            ProjectId = 24
                        },
                        new
                        {
                            Id = 75,
                            Name = "Rocks",
                            ProjectId = 24
                        },
                        new
                        {
                            Id = 76,
                            Name = "Soap base",
                            ProjectId = 25
                        },
                        new
                        {
                            Id = 77,
                            Name = "Essential oils",
                            ProjectId = 25
                        },
                        new
                        {
                            Id = 78,
                            Name = "Molds",
                            ProjectId = 25
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DIY_Site.Models.Project", b =>
                {
                    b.HasOne("DIY_Site.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DIY_Site.Models.Supply", b =>
                {
                    b.HasOne("DIY_Site.Models.Project", "Project")
                        .WithMany("Supplies")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DIY_Site.Models.Project", b =>
                {
                    b.Navigation("Supplies");
                });
#pragma warning restore 612, 618
        }
    }
}
